# Generated by Django 5.2.4 on 2025-07-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='port_location',
            field=models.CharField(default='None', help_text='Enter the port location', max_length=255),
        ),
    ]
