# Generated by Django 5.2.4 on 2025-07-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isCargoBroker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='qualifications',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
