# Generated by Django 5.2.4 on 2025-07-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_iscargobroker_user_qualifications_user_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isCargoBroker',
            new_name='is_cargo_broker',
        ),
        migrations.AlterField(
            model_name='user',
            name='qualifications',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.CharField(default='None', help_text='Only necessary for cargo brokers.', max_length=255),
        ),
    ]
