# Generated by Django 4.2.21 on 2025-07-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_iscargobroker_user_qualifications_user_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qualifications',
            field=models.CharField(default='', max_length=255),
        ),
    ]
