# Generated by Django 5.2.4 on 2025-07-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_iscargobroker_user_is_cargo_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='truck_license',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
