# Generated by Django 5.2.4 on 2025-07-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_qualifications'),
        ('accounts', '0007_user_state_user_truck_license'),
    ]

    operations = [
    ]
