# Generated by Django 5.2.4 on 2025-07-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20250715_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_cargo_broker',
            field=models.BooleanField(default=False, verbose_name='Are you a cargo broker?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='port_location',
            field=models.CharField(default='None', max_length=255, verbose_name='Port Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.CharField(default='None', help_text='(Only necessary for cargo brokers)', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='None', help_text='Examples: North Carolina, New Jersey', max_length=255, verbose_name='State on License PLate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='truck_license',
            field=models.CharField(default='None', max_length=255, verbose_name='License Plate of Truck:'),
        ),
    ]
