# Generated by Django 5.2.4 on 2025-07-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approval_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cargo_id',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='Unknown'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.IntegerField(choices=[(0, 'Hybrid'), (1, 'Pickup'), (2, 'Delivery')], default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='port_location',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='target_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
