# Generated by Django 4.2.21 on 2025-07-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucker',
            old_name='title',
            new_name='name',
        ),
    ]
