# Generated by Django 5.2.4 on 2025-07-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0002_job_approval_timestamp_job_cargo_id_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('HYBRID', 'Hybrid'), ('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], default='PICKUP', max_length=10),
        ),
    ]
