# Generated by Django 4.2.21 on 2025-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0002_rename_title_trucker_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucker',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='trucker',
            old_name='description',
            new_name='role',
        ),
        migrations.AddField(
            model_name='trucker',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
