# Generated by Django 4.2.21 on 2025-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0003_rename_name_trucker_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucker',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='trucker',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='trucker',
            name='role',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
