# Generated by Django 5.2.4 on 2025-07-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0003_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='Unknown', max_length=200),
        ),
    ]
