# Generated by Django 5.2.4 on 2025-07-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0004_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='Unknown', max_length=100),
        ),
    ]
