# Generated by Django 5.2.4 on 2025-07-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0006_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
