# Generated by Django 5.2.4 on 2025-07-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0007_job_completed_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucker',
            name='organization',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
