# Generated by Django 5.2.4 on 2025-07-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0008_trucker_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucker',
            name='qualifications',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
