# Generated by Django 5.2.4 on 2025-07-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0009_trucker_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='docking_location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='driver_applications',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='truckmanagement.trucker'),
        ),
        migrations.AddField(
            model_name='job',
            name='forSignUp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='trucker',
            name='independent_license',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='truckmanagement.trucker'),
        ),
        migrations.AlterField(
            model_name='job',
            name='license_plate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='truckmanagement.licenseplate'),
        ),
    ]
