# Generated by Django 5.2.4 on 2025-07-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0010_job_docking_location_job_driver_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='driver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='truckmanagement.trucker'),
        ),
        migrations.AlterField(
            model_name='job',
            name='license_plate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='truckmanagement.licenseplate'),
        ),
    ]
