# Generated by Django 5.2.4 on 2025-07-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0011_alter_job_driver_alter_job_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='state_locale',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
