# Generated by Django 5.2.4 on 2025-07-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0012_job_state_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplate',
            name='organization',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
