# Generated by Django 5.2.4 on 2025-07-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0013_licenseplate_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucker',
            old_name='independent_license',
            new_name='truck_license',
        ),
        migrations.AddField(
            model_name='trucker',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
