# Generated by Django 5.2.4 on 2025-07-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0014_rename_independent_license_trucker_truck_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='temp_finger',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
