# Generated by Django 5.2.4 on 2025-07-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckmanagement', '0015_job_temp_finger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cargo_id',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='Unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='port_location',
            field=models.CharField(default='Unknown', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='Pending', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='temp_finger',
            field=models.CharField(default='Pending', max_length=1000),
        ),
    ]
